### PR TITLE
Add getMinMax function in controller

### PR DESCRIPTION
**Pull request by jledentu**
This PR tries to fix the data limits issue in #29.

It looks fine but there are little layout differences in integration tests, don't know why.

### CODE REVIEW

**Comment by kurkle** [comment]
I think the getMinMax might be called before parse?

**Comment by kurkle** [comment]
The issue with `getMinMax` is that the scale does auto adjust its range after that.

**Comment by kurkle** [comment]
Took this as a base for #32 what do you think? It changes the layout to take the full chart area (by not using offset).
The `bounds: 'data'` default helps to avoid scale auto-adjusting its range.

**Comment by jledentu** [comment]
#32 Looks good to me

**Pull request closed without merging**
