### PR TITLE
FIX order of draw calls in SankeyController

### PR DESCRIPTION
**Pull request by celgra**
Canvas paints new draw operations on top of existing ones. Due to the fact that the _drawLabels method is invoked first, the text must compete with the transparent Flows drawn over it which limits the range of colors that are legible/visible (as well as fidelity of the text) within the chart. I changed the order of the calls such that _drawLabels occurs after the for expression for drawing the Flows.

### CODE REVIEW

**Comment by celgra** [comment]
My apologies, the fixtures with labels are all failing. If you would refer me to documentation for generating the png files and testing against them I would gladly work on this.

**Comment by kurkle** [comment]
You can generate them (one by one) by `npm run dev` and hitting the `debug` button on the opened browser window - and save the images from there.

**Comment by celgra** [comment]
In fixtures like labels.png that use spriteText set to true, a box with a white background is rendered as the labels. I assume this was being painted over by the Flows gradient. Is this an acceptable side effect?

**Comment by kurkle** [comment]
Yes, the fixtures have custom font rendering, because different browsers and/or platforms render fonts differently.
So the main idea is to test the text placement, not appearance as much.

So yes, its acceptable. Probably need to turn that on in the `nodeWidth` one too, so it passes.

**Comment by kurkle** [comment]
Thanks @celgra !

**Pull request merged**
